### ISSUE TITLE
Sitemap creation in blog

### ISSUE THREAD

**Issue by shahabblouch** [danielpalme/MVCBlog#11]
Do you have any plans to work on sitemap creation in the blog to make it more search engine friendly?

**Comment by danielpalme** [comment]
No I'm too busy at the moment.
But it should be straight forward to implement:

- Create a controller / endpoint with url `/sitemap.xml`
- Load all blog post urls from database
- Create XML structure
- Optional: Add output to caching

**Comment by shahabblouch** [comment]
Thanks for sharing the technical steps to implement the sitemap.
