### ISSUE TITLE
T4MVC problem

### ISSUE THREAD

**Issue by EvaSleva** [danielpalme/MVCBlog#4]
Hello, I'm having problems with T4MVC. If I Debug T4 template or Run custom tool, I get these errors that won't go away:

Error	41	A namespace cannot directly contain members such as fields or methods	C:\Users\edr\Downloads\MVCBlog-master2\MVCBlog-master\src\MVCBlog.Website\T4MVC.cs	1	1	MVCBlog.Website

Error	42	Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration	c:\Users\edr\Downloads\MVCBlog-master2\MVCBlog-master\src\MVCBlog.Website\T4MVC.tt	1	1	MVCBlog.Website

Error	43	Compiling transformation: Method must have a return type	c:\Users\edr\Downloads\MVCBlog-master2\MVCBlog-master\src\MVCBlog.Website\T4MVC.tt	1	6	MVCBlog.Website

Error	44	Compiling transformation: Type expected	c:\Users\edr\Downloads\MVCBlog-master2\MVCBlog-master\src\MVCBlog.Website\T4MVC.tt	1	12	MVCBlog.Website

Do you know anything about this?

**Comment by danielpalme** [comment]
When I download the ZIP file, I get the same error. 
When I check out the files directly from Github, it seems to work.
