### ISSUE TITLE
334 Errors

### ISSUE THREAD

**Issue by bobi33** [danielpalme/MVCBlog#5]
Hi,

When I download the zip file and try to run the solution, I get 334 errors (i.e. "The type or namespace name 'Elmah' could not be found (are you missing a using directive or an assembly reference?).

I'm using VS 2015 community and Windows 10 with anniversary update.

**Comment by danielpalme** [comment]
I just used the same setup. Seems as if packages where not restored correctly on your system. 
Does the packages directory contain a folder named "elmah.corelibrary.1.2.2"?

**Comment by bobi33** [comment]
Hi, that was correct. I repaired VS and things seem to work great now. Thanks Daniel. Now to try to implement this into an existing website :s
