### ISSUE TITLE
Search bar to search post content as well?

### ISSUE THREAD

**Issue by bobi33** [danielpalme/MVCBlog#6]
Is there any way to make the search also search the content as well, and not just the post title, etc.? I'm trying to include a wider search functionality.

**Comment by bobi33** [comment]
Also, how do you make the top bar totally disappear? I've added all of my own css to the project, as well as imported the css into the site.layout.cshtml, but the header is still too large (too much padding), even though I added my CSS files, and the black navigation bar at the top isn't going away.

**Comment by danielpalme** [comment]
If you want to extend the search functionality, take a look at the database query:
https://github.com/danielpalme/MVCBlog/blob/master/src/MVCBlog.Website/Controllers/BlogController.cs#L436

Regarding your CSS problem:
You have to figure that out yourself. I don't have the time to analyze your CSS to see which style is currently active. But if you hit F12 in your browser you can have look at the CSS rules applied to the header and see what's wrong.
