### ISSUE TITLE
TagRecords from Tags table not being removed when delete blogEntry

### ISSUE THREAD

**Issue by Darth-Fx** [danielpalme/MVCBlog#7]
When deleting a BlogEntry the EF will cascade delete the TagBlogEntries table but the Tags table isn't affected resulting in a lot of tag-orphans.
This means that the Tags section (sidebar) is stil displaying the deleted Tags (effective after an hour or application restart).

I've fixed it by adding Tag deletion code in the HandleAsync of the DeleteBlogEntryCommandHandler but maybe I'm overlooking something.....

By the way, why the 3600 cacheduration on the sidebar?
Great project!

**Comment by danielpalme** [comment]
The tags are cached for an hour and should then disappear:

https://github.com/danielpalme/MVCBlog/blob/master/src/MVCBlog.Website/Controllers/BlogController.cs#L212

**Comment by Darth-Fx** [comment]
If I just remove the Cache attribute and check, then the tags belonging to the deleted post are still visible....
But that's due to not clearing the tags of the deleted post from the DB:

https://github.com/danielpalme/MVCBlog/blob/master/src/MVCBlog.Core/Commands/BlogEntry/DeleteBlogEntryCommandHandler.cs#L19

If I include tags in this query [ .Include(c => c.Tags) ] , and remove them, then the tags are gone and not being rendered anymore.

**Comment by danielpalme** [comment]
Correct. But you have to be careful not to delete any tags that are used by other posts.
