### ISSUE TITLE
SingleOrDefault instead of FirstOrDefault in AddOrUpdateBlogEntryCommandHandler

### ISSUE THREAD

**Issue by saYRam** [danielpalme/MVCBlog#9]
```
foreach (var tag in tags.Where(t => !entry.Tags.Select(et => et.Tag.Name).Contains(t)).ToArray())
{
    var existingTag = existingTags.SingleOrDefault(t => t.Name.Equals(tag, StringComparison.OrdinalIgnoreCase));

    if (existingTag == null)
    {
        existingTag = new Tag() { Name = tag };
        existingTags.Add(existingTag);

        this.unitOfWork.Tags.Add(existingTag);
    }

    entry.Tags.Add(new BlogEntryTag()
    {
        BlogEntryId = entry.Id,
        TagId = existingTag.Id
    });
}
```
AddOrUpdateBlogEntryCommandHandler.cs line: 84

`var existingTag = existingTags.SingleOrDefault(t => t.Name.Equals(tag, StringComparison.OrdinalIgnoreCase));`

In this line SingleOrDefault will throw an exception if existingTag is null. So, it seems there is no meaning of cheking existingTag if null or not.

```
    if (existingTag == null)
    {
        existingTag = new Tag() { Name = tag };
        existingTags.Add(existingTag);

        this.unitOfWork.Tags.Add(existingTag);
    }
```

I'm just asking to learn and understand. Why didn't you use FirstOfDefault instead of SingleOrDefault? Thank you.

**Comment by danielpalme** [comment]
SingleOrDefault does not throw an exception. It returns `null` if there is no match.

See also: https://stackoverflow.com/questions/1745691/linq-when-to-use-singleordefault-vs-firstordefault-with-filtering-criteria
